--- drivers/staging/Makefile
+++ drivers/staging/Makefile
@@ -59,3 +59,4 @@ obj-$(CONFIG_TIDSPBRIDGE)	+= tidspbridge/
 obj-$(CONFIG_ACPI_QUICKSTART)	+= quickstart/
 obj-$(CONFIG_WESTBRIDGE_ASTORIA)	+= westbridge/astoria/
 obj-$(CONFIG_SBE_2T3E3)	+= sbe-2t3e3/
+obj-$(CONFIG_ATH6K_LEGACY)	+= ath6kl/
